#!/bin/bash
set -eo pipefail

version=${GOVERSION:-1.4}
srcfile=${GOFILE:-go$version.$(uname|tr A-Z a-z)-amd64.tar.gz}
url=${GOURL:-https://storage.googleapis.com/golang/$srcfile}
dist=${GODIST:-$OPENSHIFT_DIY_DIR/cache/go-$version}

if [ -d $dist/go ]; then
	echo "Use Go $version."
else
	mkdir -p $dist
	cd $dist
	echo "Installing Go $version"
	echo "Download...$url"
	curl -sO $url
	echo "Unzip..."
	tar zxf $srcfile
	rm -f $srcfile
	echo "done"
fi

export GOROOT=$dist/go
export GOPATH=$OPENSHIFT_REPO_DIR
export PATH=$GOROOT/bin:$PATH

echo "Clone etcd..."
etcd=${ETCD:-github.com/coreos/etcd}
go get $etcd

echo "Build $OPENSHFIT_APP_NAME..."
cd $GOPATH/src/github.com/coreos/etcd
go build

echo $GOROOT > $HOME/.env/user_vars/GOROOT
echo $GOPATH > $HOME/.env/user_vars/GOPATH

